dist: trusty
sudo: false

language: python
cache: pip
python:
  - "2.7"
  - "3.5"

env:
  - FQ_TEST_DB=postgresql://postgres@localhost:5432/travis_ci_test

addons:
  postgresql: "9.6"

services:
  - postgresql

install:
 - pip install tox

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'select version();' -U postgres

script:
 - tox -v -e py${TRAVIS_PYTHON_VERSION//.}
